swagger: "2.0"
info:
  description: This is a tiny url server project
  title: tiny-url-server
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths: {}